### ISSUE TITLE
Methods that return edges don't include properties

### ISSUE THREAD

**Issue by christophercliff** [Encapsule/jsgraph#53]
If I create a digraph with edges like

```js
var digraph = new DirectedGraph()
digraph.addEdge({ e: { u: 'a', v: 'b' }, p: {/* some other stuff */} })
```

Methods like `getEdges()` or `outEdges(nodeId)` return simply `Array<{ u: string, v: string }>` and I'm unable to access `{/* some other stuff */}`.

Is it possible to access that data in the current API?

**Comment by christophercliff** [comment]
I see now there is a method `getEdgeProperty({ u: vertexId, v: vertexId })`, but how would you handle the case where there are multiple edges connecting the same nodes? E.g.

```js
[
  { e: { u: 'a', v: 'b' }, p: { cost: 1 } },
  { e: { u: 'a', v: 'b' }, p: { cost: 2 } }
]
```

**Comment by ChrisRus** [comment]
Hello, @christophercliff. Nice to see you digging into this library!

As you have discovered, `DirectedGraph` methods `getEdges`, `inEdges`, and `outEdges` each return an array of zero or more objects each of which is referred to as an _edge descriptor_ object in the code. This forces you to make an explicit call to `DirectedGraph.getEdgeProperty` to retrieve each property you're interested in as you note. This seems a bit of a nuisance (note that it's like this for vertex properties as well) so I'll explain.

Explicitly, the current design is intended to discourage cached references to developer-defined vertex and edge property entities stored within the `DirectedGraph` container in derived application code. **It's actually a subtle bug** in v0.7.0 that the `getVertexProperty` and `getEdgeProperty` methods return a reference; they should rather return a deep copy I think.

The intent of this is to force derived code to always make a call through the `DirectedGraph` container API when mutating vertex and edge associated properties. vNext will include the deep copy fix above making this more than a suggestion. (So when you get a property you'll get a deep copy that you can do what you like with. If you modify it and want that change to be visible outside your storage scope, then you'll need to write the modified copy back via an explicit API method call). 

All of this is to preserve the ability to later extend `DirectedGraph` with additional functionality that allows derived code to observe graph topology and property updates via events and/or callbacks.

**Comment by ChrisRus** [comment]
Feel free to reopen this issue if you have further questions.
