### ISSUE TITLE
Can this lib be used for the sequential graph coloring algorithm implemented by boost::graph?

### ISSUE THREAD

**Issue by scmorse** [Encapsule/jsgraph#54]
This is more of a question than an issue, but does this lib port that functionality as well?

**Comment by ChrisRus** [comment]
Hello, @scmorse. 

Current v0.7.x contains only the [BGL](http://www.boost.org/doc/libs/1_57_0/libs/graph/doc/)-inspired `DirectedGraph` container class and a small collection of BGL-inspired algorithms; breadth and depth-first traversal (search and visit variants via input param options) and transpose.

Doesn't look super difficult conceptually to port the algorithm from BGL's [Sequential Vertex Coloring](http://www.boost.org/doc/libs/1_57_0/boost/graph/sequential_vertex_coloring.hpp) to JavaScript using the existing `DirectedGraph` API.

This is something you could write yourself if you were sufficiently motivated and use yourself or publish as a stand-alone package with a runtime dependency on jsgraph. Or, we could possibly collaborate to get it ported, tested, and documented for inclusion in a future release of jsgraph.

Can you comment about your use case? I'm just curious.

**Comment by ChrisRus** [comment]
... on a related note I've got a purpose-built subsystem in a jsgraph-derived project that's responsible for filtering and partitioning operations. I've been thinking it might be worth generalizing it a bit more and including it with jsgraph. Sequential coloring algorithm is a good use case of this facility perhaps. Will have to think about this a bit.

**Comment by ChrisRus** [comment]
I'll dig this up again the next time I'm in this code looking for something to do.
